name: Encrypt File

on:
  push:
    paths:
      - 'config.json'

jobs:
  encrypt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pycryptodome
          python encrypt.py ${{ secrets.AES_KEY }}

      - name: Commit encrypted file
        uses: EndBug/add-and-commit@v7
        with:
          add: 'encrypt_config'
          message: 'Add encrypted file'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: hotfix
          force: true
